### ISSUE TITLE
Support for circular computations

### ISSUE THREAD

**Issue by talegari** [r-lib/slider#194]
@DavisVaughan It would be great to have circular computations optionally in `slide` and family.

__Example use case__: Average through the hours - we need to avg `c(23, 0, 1)` hours and place it at `0`th hour.

Right now: 
```r
slider::slide_vec(1:4,
                  ~ list(.),
                  .before = 1,
                  .after = 1
                  )
``` 
gives
```
[[1]]
[1] 1 2

[[2]]
[1] 1 2 3

[[3]]
[1] 2 3 4

[[4]]
[1] 3 4
```

What is helpful:
```r
slider::slide_vec(1:4,
                  ~ list(.),
                  .before = 1,
                  .after = 1,
                  .circular = TRUE # suppose we create a new argument (say FALSE by default)
                  )
``` 

should give

```
[[1]]
[1] 4 1 2

[[2]]
[1] 1 2 3

[[3]]
[1] 2 3 4

[[4]]
[1] 3 4 1
```

**Comment by DavisVaughan** [comment]
Can you provide a real example with time based data that you were working on?

**Comment by DavisVaughan** [comment]
I'm not sure I understand how that would ever be useful, `2023-01-01 23:00:00` happens 23 hours _after_ `2023-01-01 00:00:00` so I wouldn't want it included in the window

If you had `2022-12-31 23:00:00` in your tibble instead, then you'd just use `slide_index_vec()` with `dt_col` as `.i` and supply `.before = lubridate::dhours(1)` to look back 1 hour

**Comment by talegari** [comment]
`.before = lubridate::dhours(1)` clarifies things. Thank you.
